name: rether
description: A new Flutter application.
version: 1.2.3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  http: ^0.12.0+4
  oktoast: ^2.3.1+1
  decimal: ^0.3.5
  crypto: ^2.1.3
  provider: ^4.0.4
  event_bus: ^1.1.1
  screenshot: ^0.1.1
  qr_flutter: ^3.2.0
  orientation: ^1.2.0
  barcode_scan: ^3.0.0
  synchronized: ^2.2.0
  url_launcher: ^5.4.2
  flutter_html: ^0.11.1
  path_provider: ^1.6.1
  package_info: ^0.4.0+14
  image_picker_saver: ^0.3.0
  flutter_easyrefresh: ^2.0.9
  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: icons
      fonts:
        - asset: assets/fonts/icons.ttf

    - family: EncodeSans
      fonts:
        - asset: assets/fonts/EncodeSansCondensed-Regular.ttf
        - asset: assets/fonts/EncodeSansCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/EncodeSansCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EncodeSansCondensed-Bold.ttf
          weight: 700
